name: Main CD
on:
  push:
    branches:
      - main
jobs:
  cde:
    name: Deploy to CDE
    environment:
      name: CDE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: hlm-innovation/pulumi-template
          work-dir: ./PulumiTemplate/PulumiTemplate
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}